Lunatix fixes - implements `fnd1st` and `fndnxt`
enusbaum/MBBSEmu pull request #142
Opened 2020-09-19 22:44 UTC by paladine

2020-09-20 00:31 UTC, enusbaum commented
Unit Tests are Failing

```
[xUnit.net 00:00:04.67]       Assert.Equal() Failure
[xUnit.net 00:00:04.67]       Expected: 10
[xUnit.net 00:00:04.67]       Actual:   11
[xUnit.net 00:00:04.67]       Stack Trace:
[xUnit.net 00:00:04.67]         D:\a\1\s\MBBSEmu.Tests\ExportedModules\Majorbbs\fnd1st_Tests.cs(119,0): at MBBSEmu.Tests.ExportedModules.Majorbbs.fnd1st_Tests.GetFileFromFndblk(IntPtr16 fndblkPointer)
[xUnit.net 00:00:04.67]         D:\a\1\s\MBBSEmu.Tests\ExportedModules\Majorbbs\fnd1st_Tests.cs(103,0): at MBBSEmu.Tests.ExportedModules.Majorbbs.fnd1st_Tests._EnumerateTextFiles_Test(String search)
##[error][xUnit.net 00:00:04.67]     MBBSEmu.Tests.ExportedModules.Majorbbs.fnd1st_Tests.SubDir_Test [FAIL]
[xUnit.net 00:00:04.67]         D:\a\1\s\MBBSEmu.Tests\ExportedModules\Majorbbs\fnd1st_Tests.cs(49,0): at MBBSEmu.Tests.ExportedModules.Majorbbs.fnd1st_Tests.SubDir_Test()
##[error][xUnit.net 00:00:04.68]     MBBSEmu.Tests.ExportedModules.Majorbbs.fnd1st_Tests.ModulePath_Test [FAIL]
[xUnit.net 00:00:04.68]       Assert.Equal() Failure
[xUnit.net 00:00:04.68]       Expected: 10
[xUnit.net 00:00:04.68]       Actual:   11
[xUnit.net 00:00:04.68]       Stack Trace:
```

2020-09-20 00:33 UTC, enusbaum commented
Full Log

```
2020-09-19T22:46:20.4805478Z ##[section]Starting: VSTest
2020-09-19T22:46:20.4935579Z ==============================================================================
2020-09-19T22:46:20.4936252Z Task         : Visual Studio Test
2020-09-19T22:46:20.4937269Z Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
2020-09-19T22:46:20.4938258Z Version      : 2.170.1
2020-09-19T22:46:20.4938651Z Author       : Microsoft Corporation
2020-09-19T22:46:20.4939154Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
2020-09-19T22:46:20.4939702Z ==============================================================================
2020-09-19T22:46:21.4185263Z SystemVssConnection exists true
2020-09-19T22:46:21.7327401Z SystemVssConnection exists true
2020-09-19T22:46:21.8609355Z Running tests using vstest.console.exe runner.
2020-09-19T22:46:21.8612577Z ======================================================
2020-09-19T22:46:21.8616409Z Test selector : Test assemblies
2020-09-19T22:46:21.8623898Z Test filter criteria : null
2020-09-19T22:46:21.8624900Z Search folder : D:\a\1\s
2020-09-19T22:46:21.9167407Z Action when minimum tests threshold not met : donothing
2020-09-19T22:46:21.9168601Z Minimum tests expected to be run: 0
2020-09-19T22:46:21.9169503Z VisualStudio version selected for test execution : latest
2020-09-19T22:46:21.9170864Z Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
2020-09-19T22:46:22.2273715Z Run in parallel : false
2020-09-19T22:46:22.2274991Z Run in isolation : true
2020-09-19T22:46:22.2275812Z Path to custom adapters : null
2020-09-19T22:46:22.2277328Z Other console options : null
2020-09-19T22:46:22.2278143Z Code coverage enabled : true
2020-09-19T22:46:22.2279178Z Diagnostics enabled : false
2020-09-19T22:46:22.2280892Z SystemVssConnection exists true
2020-09-19T22:46:22.2289839Z Run the tests locally using vstest.console.exe
2020-09-19T22:46:22.2290550Z ========================================================
2020-09-19T22:46:22.4018862Z Source filter: **\MBBSEmu.Tests\bin\**\MBBSEmu.Tests.dll
2020-09-19T22:46:22.6542016Z SystemVssConnection exists true
2020-09-19T22:46:22.6552064Z [command]D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.170.1\Modules\DTAExecutionHost.exe --inputFile D:\a\_temp\input_f0f0b9e0-fac9-11ea-90e0-bbe6084c5cd7.json
2020-09-19T22:46:22.6553337Z ======================================================
2020-09-19T22:46:22.6985434Z ##########################################################################
2020-09-19T22:46:22.6987122Z DtaExecutionHost version 18.170.30112.1.
2020-09-19T22:46:23.6114131Z Starting TestExecution Model...
2020-09-19T22:46:26.5408390Z Result Attachments will be stored in LogStore
2020-09-19T22:46:26.5584169Z Run Attachments will be stored in LogStore
2020-09-19T22:46:26.5663314Z Result Attachments will be stored in LogStore
2020-09-19T22:46:26.6186870Z Result Attachments will be stored in LogStore
2020-09-19T22:46:26.6188513Z Run Attachments will be stored in LogStore
2020-09-19T22:46:26.6474050Z Updated Run Settings:
2020-09-19T22:46:26.6486625Z <RunSettings>
2020-09-19T22:46:26.6487409Z   <DataCollectionRunSettings>
2020-09-19T22:46:26.6488000Z     <DataCollectors>
2020-09-19T22:46:26.6489858Z       <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKey***=b03f5f7f11d50a3a">
2020-09-19T22:46:26.6490964Z         <Configuration>
2020-09-19T22:46:26.6491644Z           <CodeCoverage>
2020-09-19T22:46:26.6492144Z             <ModulePaths>
2020-09-19T22:46:26.6494065Z               <Include>
2020-09-19T22:46:26.6494976Z                 <ModulePath>.*\.dll$</ModulePath>
2020-09-19T22:46:26.6495626Z                 <ModulePath>.*\.exe$</ModulePath>
2020-09-19T22:46:26.6496205Z               </Include>
2020-09-19T22:46:26.6496724Z               <Exclude>
2020-09-19T22:46:26.6497335Z                 <ModulePath>.*CPPUnitTestFramework.*</ModulePath>
2020-09-19T22:46:26.6497949Z               </Exclude>
2020-09-19T22:46:26.6498487Z             </ModulePaths>
2020-09-19T22:46:26.6499021Z             <Functions>
2020-09-19T22:46:26.6499549Z               <Exclude>
2020-09-19T22:46:26.6500130Z                 <Function>^Fabrikam\.UnitTest\..*</Function>
2020-09-19T22:46:26.6500794Z                 <Function>^std::.*</Function>
2020-09-19T22:46:26.6501439Z                 <Function>^ATL::.*</Function>
2020-09-19T22:46:26.6502243Z                 <Function>.*::__GetTestMethodInfo.*</Function>
2020-09-19T22:46:26.6503028Z                 <Function>^Microsoft::VisualStudio::CppCodeCoverageFramework::.*</Function>
2020-09-19T22:46:26.6503887Z                 <Function>^Microsoft::VisualStudio::CppUnitTestFramework::.*</Function>
2020-09-19T22:46:26.6504652Z               </Exclude>
2020-09-19T22:46:26.6505179Z             </Functions>
2020-09-19T22:46:26.6505708Z             <Attributes>
2020-09-19T22:46:26.6506240Z               <Exclude>
2020-09-19T22:46:26.6506881Z                 <Attribute>^System\.Diagnostics\.DebuggerHiddenAttribute$</Attribute>
2020-09-19T22:46:26.6507651Z                 <Attribute>^System\.Diagnostics\.DebuggerNonUserCodeAttribute$</Attribute>
2020-09-19T22:46:26.6508452Z                 <Attribute>^System\.Runtime\.CompilerServices\.CompilerGeneratedAttribute$</Attribute>
2020-09-19T22:46:26.6509253Z                 <Attribute>^System\.CodeDom\.Compiler\.GeneratedCodeAttribute$</Attribute>
2020-09-19T22:46:26.6510079Z                 <Attribute>^System\.Diagnostics\.CodeAnalysis\.ExcludeFromCodeCoverageAttribute$</Attribute>
2020-09-19T22:46:26.6510817Z               </Exclude>
2020-09-19T22:46:26.6511377Z             </Attributes>
2020-09-19T22:46:26.6511907Z             <Sources>
2020-09-19T22:46:26.6512433Z               <Exclude>
2020-09-19T22:46:26.6512992Z                 <Source>.*\\atlmfc\\.*</Source>
2020-09-19T22:46:26.6513619Z                 <Source>.*\\vctools\\.*</Source>
2020-09-19T22:46:26.6514246Z                 <Source>.*\\public\\sdk\\.*</Source>
2020-09-19T22:46:26.6514984Z                 <Source>.*\\microsoft sdks\\.*</Source>
2020-09-19T22:46:26.6515638Z                 <Source>.*\\vc\\include\\.*</Source>
2020-09-19T22:46:26.6516225Z               </Exclude>
2020-09-19T22:46:26.6516755Z             </Sources>
2020-09-19T22:46:26.6517341Z             <CompanyNames>
2020-09-19T22:46:26.6517886Z               <Exclude>
2020-09-19T22:46:26.6518479Z                 <CompanyName>.*microsoft.*</CompanyName>
2020-09-19T22:46:26.6519077Z               </Exclude>
2020-09-19T22:46:26.6519613Z             </CompanyNames>
2020-09-19T22:46:26.6520677Z             <PublicKey***s>
2020-09-19T22:46:26.6521223Z               <Exclude>
2020-09-19T22:46:26.6522359Z                 <PublicKey***>^B77A5C561934E089$</PublicKey***>
2020-09-19T22:46:26.6534166Z                 <PublicKey***>^B03F5F7F11D50A3A$</PublicKey***>
2020-09-19T22:46:26.6535989Z                 <PublicKey***>^31BF3856AD364E35$</PublicKey***>
2020-09-19T22:46:26.6538135Z                 <PublicKey***>^89845DCD8080CC91$</PublicKey***>
2020-09-19T22:46:26.6540517Z                 <PublicKey***>^71E9BCE111E9429C$</PublicKey***>
2020-09-19T22:46:26.6548639Z                 <PublicKey***>^8F50407C4E9E73B6$</PublicKey***>
2020-09-19T22:46:26.6550016Z                 <PublicKey***>^E361AF139669C375$</PublicKey***>
2020-09-19T22:46:26.6550718Z               </Exclude>
2020-09-19T22:46:26.6551533Z              [...]

2020-09-20 13:10 UTC, enusbaum commented
Getting this when I run the tests locally:

```
System.AggregateException
One or more errors occurred. (Access to the path 'C:\Users\Eric\AppData\Local\Temp\fnd1st\test.dat' is denied.) (Access to the path '\\?\C:\Users\Eric\AppData\Local\Temp\fnd1st\' is denied.)
  Exception doesn't have a stacktrace

System.UnauthorizedAccessException
Access to the path 'C:\Users\Eric\AppData\Local\Temp\fnd1st\test.dat' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at MBBSEmu.Tests.ExportedModules.Majorbbs.fnd1st_Tests.CreateFile(String file) in C:\Users\Eric\Documents\GitHub\MBBSEmu\MBBSEmu.Tests\ExportedModules\Majorbbs\fnd1st_Tests.cs:line 135
   at MBBSEmu.Tests.ExportedModules.Majorbbs.fnd1st_Tests.ExactMatch_Test() in C:\Users\Eric\Documents\GitHub\MBBSEmu\MBBSEmu.Tests\ExportedModules\Majorbbs\fnd1st_Tests.cs:line 74

System.UnauthorizedAccessException
Access to the path '\\?\C:\Users\Eric\AppData\Local\Temp\fnd1st\' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at MBBSEmu.Tests.ExportedModules.Majorbbs.fnd1st_Tests.Dispose() in C:\Users\Eric\Documents\GitHub\MBBSEmu\MBBSEmu.Tests\ExportedModules\Majorbbs\fnd1st_Tests.cs:line 27
   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 31
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass47_0.<RunAsync>b__1() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 216
   at Xunit.Sdk.ExceptionAggregator.Run(Action code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 73
```

2020-09-20 13:39 UTC, enusbaum requested changes
Test Execution Issues, otherwise looks good!

2020-09-20 19:19 UTC, paladine commented
Fixed and verified tests pass on both Linux & Win32

2020-09-21 12:28 UTC, enusbaum approved these changes
Wooooooo! 👍

2020-09-21 12:28 UTC, merged