`cncint` `cnclon` and `cncnum` fixes
enusbaum/MBBSEmu pull request #193
Opened 2020-10-13 14:45 UTC by paladine

Adds an integration test with an updated `MBBSEMU.DLL` as well. Module uses `cnclon` to extract a value and writes it to btrieve, so also helps test the btrieve insertion code.

2020-10-13 21:00 UTC, enusbaum requested changes

2020-10-14 01:42 UTC, paladine commented on MBBSEmu.Tests/Integration/BtrievePrint_Tests.cs
> +            foreach (char c in s)
That's a negative Ghost Rider

2020-10-14 01:43 UTC, paladine commented on MBBSEmu/HostProcess/ExportedModules/ExportedModuleBase.cs
> +            public String StringValue { get; set; }
Intermixing Java & C# is confusing

2020-10-14 02:48 UTC, paladine commented on MBBSEmu/HostProcess/ExportedModules/ExportedModuleBase.cs
> +            result.Valid = Int32.TryParse(result.StringValue, out var value);
not following on this one

2020-10-14 03:02 UTC, enusbaum commented on MBBSEmu/HostProcess/ExportedModules/ExportedModuleBase.cs
> +            result.Valid = Int32.TryParse(result.StringValue, out var value);
int.TryParse()

2020-10-14 10:26 UTC, enusbaum approved these changes

2020-10-14 10:26 UTC, merged