Add stzcpy and l2as tests
enusbaum/MBBSEmu pull request #219
Opened 2020-10-27 02:55 UTC by tuday2

2020-10-27 03:13 UTC, paladine requested changes

2020-10-27 03:13 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/l2as_Tests.cs
> +        public void L2ASTest(ushort inputLow, ushort inputHigh, string expectedValue)
can you pass these in as ints instead of two shorts?

2020-10-27 03:13 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/l2as_Tests.cs
> +        [InlineData(0x0, 0x7FFF, "2147418112")]
how about some negative numbers as well?

2020-10-27 03:13 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/stzcpy_Tests.cs
> +                    copyLength
dstLength is the arg to stzcpy, e.g. stzcpy(char *dst, char *src, int dstLength);

We also want to verify that any remaining bytes in dst are zero filled at the end, e.g. if you do this

```
char buf[32];
stzcpy(buf, "test", sizeof(buf));
```

buf would have the string "test" and all remaining zeros after it. So validating the zeros is an important assertion to make for this API call

2020-10-27 03:13 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/l2as_Tests.cs
> +        public void L2ASTest(ushort inputLow, ushort inputHigh, string expectedValue)
As in one single 32-int vs two 16-bit shorts

2020-10-28 03:31 UTC, tuday2 commented
Changed Ordinal and now passes tests I setup based on documentation -- thoughts?

![STZCOPY](https://user-images.githubusercontent.com/27604078/97387498-1cb10b00-18a4-11eb-84cc-a7475730d2fc.jpg)

2020-10-28 15:59 UTC, paladine approved these changes

2020-10-28 15:59 UTC, paladine commented on MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs
> +            }
wouldn't `--limit` suffice?

2020-10-28 15:59 UTC, paladine commented on MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs
> +            inputBuffer.WriteByte(0x0);;
nit: extraneous semicolon

2020-10-28 18:13 UTC, tuday2 commented
Fixed and ready for merge

2020-10-28 18:30 UTC, paladine approved these changes

2020-10-28 18:35 UTC, merged