Added new Sysop commands, formatting
enusbaum/MBBSEmu pull request #276
Opened 2020-11-08 15:37 UTC by tuday2

-Kick <user>
-Broadcast <message>
-Cleanup
-Cleanuped up formatting in globals

2020-11-09 00:19 UTC, enusbaum requested changes

2020-11-09 00:19 UTC, enusbaum commented on MBBSEmu/HostProcess/GlobalRoutines/SysopGlobal.cs
> +                if (channelToKick != null)
`FirstOrDefault` will return null if no record is found.

You can invert this IF statement where if `channelToKick == null` display error and return. Would reduce nesting.

2020-11-09 00:19 UTC, enusbaum commented on MBBSEmu/HostProcess/MbbsHost.cs
> +            var globalCleanup = (_globalCache.Get("SYSOPGLOBAL-CLEANUP") as bool?).GetValueOrDefault();
Do a `TryGet` on the cache, cleans up this statement

2020-11-09 00:19 UTC, enusbaum commented on MBBSEmu/Program.cs
> +                globalCache.Set("SYSOPGLOBAL-CLEANUP", false);
If you change the code in MbbsHost to the TryGet<T> you don't need to set an initial value

2020-11-09 02:10 UTC, tuday2 commented
Fixed -- ready for review

2020-11-10 02:35 UTC, enusbaum approved these changes

2020-11-10 02:35 UTC, merged