Implement Btrieve ACS
enusbaum/MBBSEmu pull request #298
Opened 2020-11-16 17:18 UTC by paladine

- Implements Btrieve ACS functionality + adds relevant tests
- Adds a version number to the Btrieve database for schema compatibility
- Speeds up unit tests by using a shared in memory account db for unit tests (not just integration)
- Handles database `Stream` reads to make sure we read the entire `Stream`

2020-11-16 17:19 UTC, paladine commented
- Also added a `Seek` cursor direction for `KeyEqual` queries, instead of using that hack `>=` query + manual key validation. Manual key validation would have been more difficult given ACS. Makes sense to just let sqlite do it

2020-11-18 16:01 UTC, enusbaum requested changes
formatting changes

2020-11-18 16:01 UTC, enusbaum commented on MBBSEmu/Btrieve/BtrieveKey.cs
> +        public bool RequiresACS { get => Segments.Any(segment => segment.RequiresACS); }
same as below

2020-11-18 16:01 UTC, enusbaum commented on MBBSEmu/Btrieve/BtrieveUtil.cs
> +            int totalRead = 0;
var

2020-11-18 16:01 UTC, enusbaum commented on MBBSEmu/Btrieve/BtrieveUtil.cs
> +            byte[] buffer = new byte[s.Length];
var

2020-11-18 23:21 UTC, paladine commented on MBBSEmu.Tests/Btrieve/BtrieveKey_Tests.cs
> +            var key = new BtrieveKey() {
TIL

2020-11-19 01:18 UTC, merged