Change Btrieve cache to a bounded LRU cache
enusbaum/MBBSEmu pull request #329
Opened 2020-12-15 20:34 UTC by paladine

Should be ready for review. @tuday2 maybe you can get get some metrics on memory comparisons with your large config?

2020-12-15 22:30 UTC, tuday2 commented
**31 modules**

**Before**
![image](https://user-images.githubusercontent.com/27604078/102280405-b7b48180-3ef2-11eb-8fbd-ded70453b07d.png)

**After**
![image](https://user-images.githubusercontent.com/27604078/102280412-bb480880-3ef2-11eb-8804-4ead35fd8310.png)

2020-12-15 22:43 UTC, tuday2 commented on MBBSEmu/Configuration.cs
Unnecessary blank line

2020-12-15 22:43 UTC, tuday2 commented on MBBSEmu/Configuration.cs
Also I added screenshots of the before/after to the PR. Everything seems to function fine.

2020-12-17 03:03 UTC, enusbaum requested changes

2020-12-17 03:03 UTC, enusbaum commented on MBBSEmu/Util/LRUCache.cs
> +        value = default(TValue);
you should be able to simplify this to just `value = default`

2020-12-17 03:03 UTC, enusbaum commented on MBBSEmu/Util/LRUCache.cs
> +    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => throw new NotSupportedException();
We can just import `System.Collections`

2020-12-17 16:11 UTC, paladine commented on MBBSEmu/Util/LRUCache.cs
> +    public bool IsReadOnly { get => false; }
Required as part of `IDictionary`

2020-12-17 20:41 UTC, enusbaum approved these changes

2020-12-17 20:41 UTC, merged