Added condex() ordinal 137
enusbaum/MBBSEmu pull request #331
Opened 2020-12-18 04:02 UTC by tuday2

Closes #299

2020-12-18 18:02 UTC, enusbaum commented
Add Unit Tests and we're good to go on this one! 👍

2020-12-20 04:05 UTC, tuday2 commented
Condex() test done, ready for initial review

2020-12-20 14:32 UTC, enusbaum requested changes

2020-12-20 14:32 UTC, enusbaum commented on MBBSEmu/HostProcess/Structs/UidxrefStruct.cs
> +                return xrfstgSpan.Slice(0, XRFSIZ + 1).ToArray();
You can one line these getters as `get => new ReadOnlySpan<byte>(Data).Slice(xyz).ToArray();`

2020-12-20 14:32 UTC, enusbaum commented on MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs
> +                userXref.userid = Encoding.ASCII.GetBytes(userAccount.userName);
null terminate these using `+ "\0"`

2020-12-20 14:32 UTC, enusbaum commented on MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs
> +            Module.Memory.AllocateVariable("UIDXRF", 0x34, true); //52 bytes for uidxrf struct
use the const struct `Size` for the value here vs. 0x34

2020-12-20 15:11 UTC, enusbaum requested changes

2020-12-20 15:11 UTC, enusbaum commented on MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs
> +                userXref.xrfstg = Encoding.ASCII.GetBytes(searchUserName);
Null terminate these as well

2020-12-20 15:11 UTC, enusbaum commented on MBBSEmu/HostProcess/Structs/UidxrefStruct.cs
> +            get => new ReadOnlySpan<byte>(Data).Slice(0, XRFSIZ + 1).ToArray();
Why is this one +1?

2020-12-20 15:11 UTC, enusbaum commented on MBBSEmu/HostProcess/Structs/UidxrefStruct.cs
> +        public const int SPARESIZ = 6; // spare
Based on adding these up, the `Size` should be 51 -- right?

2020-12-20 21:48 UTC, merged

2020-12-20 23:10 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/condex_Tests.cs
> +        public void condex_Test()
should have a test without the CONDEX flag set as well