nctime() test, ordinal update
enusbaum/MBBSEmu pull request #350
Opened 2020-12-27 13:58 UTC by tuday2

-1 second off if odd second

```
            //From DOSFACE.H:
            //#define dttime(hour,min,sec) (((hour)<<11)+((min)<<5)+((sec)>>1))
            //var packedTime = (_clock.Now.Hour << 11) + (_clock.Now.Minute << 5) + (_clock.Now.Second >> 1);
```

PHP program I found
```php
/** Converts DOS time to Unix time */
function dosToUnixTime($dosTime) {
  $date = mktime(
    (($dosTime >> 11) & 0x1f), // hours
    (($dosTime >> 5) & 0x3f),  // minutes
    (($dosTime << 1) & 0x3e),  // seconds
    ((($dosTime >> 21) & 0x0f) - 1),   // month
    (($dosTime >> 16) & 0x1f),         // day
    ((($dosTime >> 25) & 0x7f) + 1980) // year
```

Reference from MSDN:
![image](https://user-images.githubusercontent.com/27604078/103172438-0c23ff00-4819-11eb-9116-a2161bd1e75b.png)

2020-12-27 18:20 UTC, tuday2 commented
https://github.com/microsoft/MS-DOS/blob/04a3d20ff411409ab98474892b2bb1713bde0f7f/v2.0/source/COPYPROC.ASM

Confirmed seconds are divided by 2 when packed

2020-12-27 21:28 UTC, paladine requested changes

2020-12-27 21:28 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/nctime_Tests.cs
> +        [InlineData(23, 59, 58, "23:59:58", true)]
need a test with an odd second value

2020-12-27 21:28 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/now_Tests.cs
> +        [InlineData(23, 59, 58)]
ditto

2020-12-27 21:28 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/time_Tests.cs
> +            Assert.Equal(expectedUnixDate >> 16, mbbsEmuCpuRegisters.DX);
could use `mbbsEmuCpuRegisters.GetLong` here instead of two assertions?

2020-12-27 21:28 UTC, paladine commented on MBBSEmu.Tests/ExportedModules/Majorbbs/nctime_Tests.cs
> +            if (allocateNCTIME)
could you also tweak the `nctime` implementation and replace `if (!TryGetVariable("NCTIME")) { AllocateVariable(); `

with a single `GetOrAllocateVariablePointer`?

2020-12-28 16:05 UTC, paladine approved these changes

2020-12-28 16:05 UTC, merged