add SYSTEM_NAME textvar
enusbaum/MBBSEmu pull request #364
Opened 2021-01-02 17:10 UTC by tuday2

-fixes farwest trivia crash

2021-01-02 17:30 UTC, paladine requested changes

2021-01-02 17:30 UTC, paladine commented on MBBSEmu/HostProcess/ExportedModules/Majorbbs.cs
> +            Module.Memory.SetArray("SYSTEM_NAME", Encoding.ASCII.GetBytes(_configuration.BBSTitle));
If the bbs title is 32 chars or greater it will Overflow the buffer, yes?

Limit to 31 to ensure a null terminator

2021-01-02 17:37 UTC, paladine reviewed
How does this fix a bug? The new variable isn't exposed anywhere?

2021-01-02 18:01 UTC, tuday2 commented
```
2021-01-02 10:47:02.3892 Error MBBSEmu.HostProcess.ExportedModules.ExportedModuleBase.ProcessTextVariables Unknown Text Variable: SYSTEM_NAME
Unhandled exception. System.Exception: Unsupported Operation Size
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(FarPtr entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(FarPtr entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()
   ```

2021-01-03 15:07 UTC, paladine requested changes
LGTM - needs tests for the opcodes

2021-01-04 00:29 UTC, enusbaum approved these changes

2021-01-04 00:30 UTC, merged